export const browserCoreExamples = [
  "mazelclaw browser status",
  "mazelclaw browser start",
  "mazelclaw browser stop",
  "mazelclaw browser tabs",
  "mazelclaw browser open https://example.com",
  "mazelclaw browser focus abcd1234",
  "mazelclaw browser close abcd1234",
  "mazelclaw browser screenshot",
  "mazelclaw browser screenshot --full-page",
  "mazelclaw browser screenshot --ref 12",
  "mazelclaw browser snapshot",
  "mazelclaw browser snapshot --format aria --limit 200",
  "mazelclaw browser snapshot --efficient",
  "mazelclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "mazelclaw browser navigate https://example.com",
  "mazelclaw browser resize 1280 720",
  "mazelclaw browser click 12 --double",
  'mazelclaw browser type 23 "hello" --submit',
  "mazelclaw browser press Enter",
  "mazelclaw browser hover 44",
  "mazelclaw browser drag 10 11",
  "mazelclaw browser select 9 OptionA OptionB",
  "mazelclaw browser upload /tmp/mazelclaw/uploads/file.pdf",
  'mazelclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "mazelclaw browser dialog --accept",
  'mazelclaw browser wait --text "Done"',
  "mazelclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "mazelclaw browser console --level error",
  "mazelclaw browser pdf",
];
