name: MazelClaw
options:
  bundleIdPrefix: ai.mazelclaw
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"

packages:
  MazelClawKit:
    path: ../shared/MazelClawKit
  Swabble:
    path: ../../Swabble

schemes:
  MazelClaw:
    shared: true
    build:
      targets:
        MazelClaw: all
    test:
      targets:
        - MazelClawTests

targets:
  MazelClaw:
    type: application
    platform: iOS
    configFiles:
      Debug: Signing.xcconfig
      Release: Signing.xcconfig
    sources:
      - path: Sources
    dependencies:
      - target: MazelClawShareExtension
        embed: true
      - target: MazelClawWatchApp
      - package: MazelClawKit
      - package: MazelClawKit
        product: MazelClawChatUI
      - package: MazelClawKit
        product: MazelClawProtocol
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    preBuildScripts:
      - name: SwiftFormat (lint)
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftformat >/dev/null 2>&1; then
            echo "error: swiftformat not found (brew install swiftformat)" >&2
            exit 1
          fi
          swiftformat --lint --config "$SRCROOT/../../.swiftformat" \
            --filelist "$SRCROOT/SwiftSources.input.xcfilelist"
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftlint >/dev/null 2>&1; then
            echo "error: swiftlint not found (brew install swiftlint)" >&2
            exit 1
          fi
          swiftlint lint --config "$SRCROOT/.swiftlint.yml" --use-script-input-file-lists
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_ENTITLEMENTS: Sources/MazelClaw.entitlements
        CODE_SIGN_STYLE: "$(MAZELCLAW_CODE_SIGN_STYLE)"
        DEVELOPMENT_TEAM: "$(MAZELCLAW_DEVELOPMENT_TEAM)"
        PRODUCT_BUNDLE_IDENTIFIER: "$(MAZELCLAW_APP_BUNDLE_ID)"
        PROVISIONING_PROFILE_SPECIFIER: "$(MAZELCLAW_APP_PROFILE)"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        ENABLE_APPINTENTS_METADATA: NO
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: MazelClaw
        CFBundleIconName: AppIcon
        CFBundleURLTypes:
          - CFBundleURLName: ai.mazelclaw.ios
            CFBundleURLSchemes:
              - mazelclaw
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIBackgroundModes:
          - audio
          - remote-notification
        BGTaskSchedulerPermittedIdentifiers:
          - ai.mazelclaw.ios.bgrefresh
        NSLocalNetworkUsageDescription: MazelClaw discovers and connects to your MazelClaw gateway on the local network.
        NSAppTransportSecurity:
          NSAllowsArbitraryLoadsInWebContent: true
        NSBonjourServices:
          - _mazelclaw-gw._tcp
        NSCameraUsageDescription: MazelClaw can capture photos or short video clips when requested via the gateway.
        NSLocationWhenInUseUsageDescription: MazelClaw uses your location when you allow location sharing.
        NSLocationAlwaysAndWhenInUseUsageDescription: MazelClaw can share your location in the background when you enable Always.
        NSMicrophoneUsageDescription: MazelClaw needs microphone access for voice wake.
        NSSpeechRecognitionUsageDescription: MazelClaw uses on-device speech recognition for voice wake.
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  MazelClawShareExtension:
    type: app-extension
    platform: iOS
    configFiles:
      Debug: Signing.xcconfig
      Release: Signing.xcconfig
    sources:
      - path: ShareExtension
    dependencies:
      - package: MazelClawKit
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: "$(MAZELCLAW_CODE_SIGN_STYLE)"
        DEVELOPMENT_TEAM: "$(MAZELCLAW_DEVELOPMENT_TEAM)"
        PRODUCT_BUNDLE_IDENTIFIER: "$(MAZELCLAW_SHARE_BUNDLE_ID)"
        PROVISIONING_PROFILE_SPECIFIER: "$(MAZELCLAW_SHARE_PROFILE)"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
    info:
      path: ShareExtension/Info.plist
      properties:
        CFBundleDisplayName: MazelClaw Share
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).ShareViewController"
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsText: true
              NSExtensionActivationSupportsWebURLWithMaxCount: 1
              NSExtensionActivationSupportsImageWithMaxCount: 10
              NSExtensionActivationSupportsMovieWithMaxCount: 1

  MazelClawWatchApp:
    type: application.watchapp2
    platform: watchOS
    deploymentTarget: "11.0"
    sources:
      - path: WatchApp
    dependencies:
      - target: MazelClawWatchExtension
    configFiles:
      Debug: Config/Signing.xcconfig
      Release: Config/Signing.xcconfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "$(MAZELCLAW_WATCH_APP_BUNDLE_ID)"
    info:
      path: WatchApp/Info.plist
      properties:
        CFBundleDisplayName: MazelClaw
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
        WKCompanionAppBundleIdentifier: "$(MAZELCLAW_APP_BUNDLE_ID)"
        WKWatchKitApp: true

  MazelClawWatchExtension:
    type: watchkit2-extension
    platform: watchOS
    deploymentTarget: "11.0"
    sources:
      - path: WatchExtension/Sources
    dependencies:
      - sdk: WatchConnectivity.framework
      - sdk: UserNotifications.framework
    configFiles:
      Debug: Config/Signing.xcconfig
      Release: Config/Signing.xcconfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "$(MAZELCLAW_WATCH_EXTENSION_BUNDLE_ID)"
    info:
      path: WatchExtension/Info.plist
      properties:
        CFBundleDisplayName: MazelClaw
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
        NSExtension:
          NSExtensionAttributes:
            WKAppBundleIdentifier: "$(MAZELCLAW_WATCH_APP_BUNDLE_ID)"
          NSExtensionPointIdentifier: com.apple.watchkit

  MazelClawTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: MazelClaw
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.mazelclaw.ios.tests
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/MazelClaw.app/MazelClaw"
        BUNDLE_LOADER: "$(TEST_HOST)"
    info:
      path: Tests/Info.plist
      properties:
        CFBundleDisplayName: MazelClawTests
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
